BEGIN; -- Transaction : si l'une des étapes fail, les autres sont restaurées

-- On supprime les tables avant de les re-créergi stutus
DROP TABLE IF EXISTS "user", "reservation", "category", "attraction", "attraction_category";

-- Création de la table "user"
CREATE TABLE "user" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "firstname" VARCHAR(50) NOT NULL,
    "lastname" VARCHAR(50) NOT NULL,
    "email" VARCHAR(100) UNIQUE NOT NULL,
    "password" VARCHAR(255) NOT NULL, 
    "profil_image" VARCHAR(255),
    "pseudo" VARCHAR(50),
    "adress" VARCHAR(50),
    "postal_code" VARCHAR(20),
    "city"VARCHAR(50),
    "role" TEXT DEFAULT 'member',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
);

-- Création de la table reservation
CREATE TABLE "reservation" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER REFERENCES "user"(id) ON DELETE CASCADE,
    "ref_number" INTEGER NOT NULL UNIQUE,
    "date" DATE NOT NULL,
    "ticket" INTEGER NOT NULL,
    "total_price" DECIMAL(10, 2) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
);

-- Création de la table category
CREATE TABLE "category" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(50) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
);

-- Création de la table attraction
CREATE TABLE "attraction" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(50) NOT NULL,
    "image" VARCHAR(255),
    "description_short" TEXT NOT NULL,
    "description_long" TEXT NOT NULL,
    "opening_time" TIME NOT NULL,
    "closing_time" TIME NOT NULL,
    "disable_access" TEXT NOT NULL,
    "weather_hazard" TEXT NOT NULL,
    "height_restriction" DECIMAL(4, 2) NOT NULL,
    "health_hazard" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ,
    "caroussel1" VARCHAR(255),
    "caroussel2" VARCHAR(255),
    "caroussel3" VARCHAR(255)
);

-- Création de la table attraction_category
CREATE TABLE "attraction_category" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "attraction_id" INTEGER REFERENCES attraction(id) ON DELETE CASCADE,
    "category_id" INTEGER REFERENCES category(id) ON DELETE CASCADE,
UNIQUE ("attraction_id", "category_id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
);

COMMIT;
